# Generated by Django 4.0.1 on 2022-02-07 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
    ]
