# Generated by Django 4.0.1 on 2022-02-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_blog_author_blog_image_blog_subtitle_blog_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=200)),
                ('subheading', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField()),
                ('author', models.TextField(blank=True, default='')),
                ('footnote', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
